version: '3.4'

services:
  # theobu:
  #  image: theobu
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  ports:
  #    - "4300:80"
    #restart: always
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres: