name: Test
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: npm install, build
      run: |
        # Build the project
        npm install
        npm run build --if-present
      working-directory: './theobu.frontend/'
    - name: GitHub Branch Deploy
      uses: zekth/gh-deploy-action@1.0.0
      with:
        dir: './theobu.frontend/dist/theobu'
        gh_token: ${{ secrets.GH_TOKEN }}
